### ISSUE TITLE
Missing closing quotes

### ISSUE THREAD

**Issue by divideddarko** [Ignaciox/Cleandows-10#2]
**File**: Cleandows-10/Disable_Onedrive.ps1

Tried to run the code, but got the following error: 

> The string is missing the terminator: ".
> At line:0 char:0

On review this looks like an issue with **line 56**

`Write-Output "Waiting for explorer to complete `

Fix: 

`Write-Output "Waiting for explorer to   ##complete" `

**Comment by Veixlix** [comment]
Fixed thank you.
